local M = {}

M.md_icons = {
	ui = {
		close = "󱎘",
		quit = "󰍃",
		arrow_right = "󰳟",
		-- arrow_right = "󰬪",
		arrow_left = "󰳝",
		-- arrow_left = "󰬨",
	},

	git = {
		-- added = "󰐙",
		added = "󰐗",
		-- added = "󰐖",
		branch = "",
		-- conflict = "󱨧",
		conflict = "󱡝",
		diff = "󰆗",
		ignored = "󱥸",
		-- modified = "󰻃",
		modified = "󰪥",
		-- modified = "󰻂",
		octoface = "",
		-- removed = "󰜺",
		removed = "󰍶",
		-- removed = "󰍵",
		-- renamed = "󰮍",
		renamed = "󰟃",
		repo = "",
		-- staged = "󰬭",
		staged = "󰬬",
		tag = "",
		-- unstaged = "󰬧",
		unstaged = "󰬦",
		-- untracked = "󰄰",
		untracked = "󰋗",
		logo = "󰊤",
	},

	diagnostics = {
		error = "󰅙",
		hint = "󰌵",
		-- hint = "󱤅",
		info = "󰋼",
		ques = "󰋗",
		warn = "󰀦",
		-- warn = "󰀨",
		debug = "󰃤",
		trace = "",
	},

	documents = {
		file = "󰈔",
		file_writtened = "",
		file_import = "󰈠",
		file_find = "󰱼",
		file_add = "󰝒",
		file_recent = "󱋡",
		text_find = "󱎸",
		folders = "󰉓",
		folder_closed = "󰉋",
		folder_opened = "󰝰",
		folder_empty = "󰉖",
		folder_tree = "󰙅",
		modified = "󰑊",
		-- modified = "",
		-- modified = "󰑊",
		-- modified = "󰪥",
		hidden = "󰈉",
	},

	others = {
		init = "󰟒",
		key = "󰌆",
		-- start = "󰐊",
		start = "󰗍",
		setting = "󰒓",
		-- setting = "󰣖",
		server = "󰇖",
		restore = "󰑌",
		-- restore = "󱍷",
		-- restore = "󱍸",
		mark = "󰍎",
		layer_find = "󱈆",
		session_find = "󱈅",
		-- session_find = "󰛔",
		flash = "󰉁",
		pin = "󰐃",
		terminal = "",
		favorite = "󰓎",
		-- favorite = "󰫢",
		sleep = "󰒲",
		loaded = "󰗠",
		pending = "󰟃",
		not_loaded = "󰄯",
		plugin = "󰐱",
		-- plugin = "󱊈",
		-- plugin = "󱘖",
		runtime = "󰓅",
		require = "󰢱",
		-- require = "󰃀",
		source = "󰐤",
		-- source = "󰆦",
		task = "󱃔",
		toggle_on = "󰔡",
		toggle_off = "󰨙",
		label = "󰌕",
		save = "󰆓",
		buffers = "󰀻",
		vim = "",
		neovim = "",
		record = "󰑊",
	},
}

M.fa_icons = {
	git = {
		add = "",
		remove = "",
		mod = "",
		rename = "",
		untrack = "",
		ignore = "",
		unstage = "",
		stage = "",
		conflict = "",
		logo = "",
	},

	diagnostics = {
		hint = "",
		error = "",
		info = "",
		warn = "",
		debug = "",
		trace = "",
	},

	documents = {
		folder_closed = "",
		folder_opened = "",
		folder_empty = "",
		folder_tree = "",
	},

	others = {
		buffers = "",
	},
}

M.kind = {
	file = " ",
	module = " ",
	namespace = " ",
	package = " ",
	class = " ",
	method = " ",
	property = " ",
	field = " ",
	constructor = " ",
	enum = " ",
	interface = " ",
	functions = " ",
	variable = " ",
	constant = " ",
	number = " ",
	boolean = " ",
	array = " ",
	object = " ",
	key = " ",
	null = " ",
	enumMember = " ",
	struct = " ",
	event = " ",
	operator = " ",
	typeParameter = " ",
	color = " ",
	folder = " ",
	keyword = " ",
	reference = " ",
	snippet = " ",
	text = " ",
	unit = " ",
	value = " ",
}

M.separators = {
	left_1 = "",
	right_1 = "",
	right_2 = "╲",
	left_2 = "╱",
	left_3 = "▏", -- used only in lualine besides scrollbar
	right_3 = "▕", -- used only in lualine besides scrollbar
	-- left = "🙽",
	-- right = "🙼",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "▓▒░",
	-- right = "░▒▓",
}

M.indent = {
	char = "│",
	last_char = "╰",
	bottom_char = "─",
}

return M
