# don't need to modify this file. it was generated by "nixos-generate-config" and may be overwritted by future invocations. please make changes to "/etc/nixos/configuration.nix" file instead
{ config, lib, pkgs, modulesPath, ... }:
{
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];
	boot = {
		initrd = {
			availableKernelModules = [
				"xhci_pci"
					"ahci"
					"nvme"
					"usbhid"
					"usb_storage"
					"sd_mod"
			];
			kernelModules = [ ];
		};
		kernelModules = [
			"kvm-intel"
		];
		extraModulePackages = [ ];
	};
	fileSystems = {
		"/" = {
			device = "/dev/disk/by-label/nixos";
			fsType = "ext4";
		};
		"/boot" = {
			device = "/dev/disk/by-label/BOOT";
			fsType = "vfat";
			options = [
				"fmask=0022"
					"dmask=0022"
			];
		};
	};
	swapDevices = [
	{
		device = "/dev/disk/by-label/swap";
	}
	];
	networking = {
		useDHCP = lib.mkDefault true; # enables DHCP on each ethernet and wireless interfaces
		# interfaces = {
		#   eno2 = {
		#     useDHCP = lib.mkDefault true;
		#   };
		#   wlo1 = {
		#     useDHCP = lib.mkDefault true;
		#   };
		# };
	};
	nixpkgs = {
		hostPlatform = lib.mkDefault "x86_64-linux";
	};
	hardware = {
		cpu = {
			intel = {
				updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
			};
		};
	};
}

