local M = {};

M.ui = {
  border = {
    top = {
      left = "╭",
      right = "╮",
    },
    bottom = {
      left = "╰",
      right = "╯",
    },
    horizontal = "─",
    vertical = "│",
  },
	close = "󱎘",
	quit = "󰍃",
  arrow = {
	  left = "󰳝",
	  -- left = "󰬨",
	  right = "󰳟",
	  -- right = "󰬪",
  },
};

M.git = {
	-- added = "󰐙",
	added = "󰐗",
	-- added = "󰐖",
	branch = "",
	-- conflict = "󱨧",
	conflict = "󱡝",
	diff = "󰆗",
	ignored = "󱥸",
	-- modified = "󰻃",
	modified = "󰪥",
	-- modified = "󰻂",
	octoface = "",
	-- removed = "󰜺",
	removed = "󰍶",
	-- removed = "󰍵",
	-- renamed = "󰮍",
	renamed = "󰟃",
	repo = "",
	-- staged = "󰬭",
	staged = "󰬬",
	tag = "",
	-- unstaged = "󰬧",
	unstaged = "󰬦",
	-- untracked = "󰄰",
	untracked = "󰋗",
	logo = "󰊤",
};

M.diagnostics = {
	error = "󰅙",
	hint = "󰌵",
	-- hint = "󱤅",
	info = "󰋼",
	ques = "󰋗",
	warn = "󰀦",
	-- warn = "󰀨",
	debug = "󰃤",
	trace = "",
};

M.documents = {
  file = {
		add = "󰝒",
    default = "󰈔",
		written = "",
		import = "󰈠",
		find = "󰱼",
		recent = "󱋡",
  },
  folder = {
    multi = "󰉓",
		closed = "󰉋",
		opened = "󰝰",
		empty = "󰉖",
		tree = "󰙅",
  },
};

M.extras = {
  find = {
	  layer = "󱈆",
	  session = "󱈅",
	  -- session = "󰛔",
  },
  editor = {
	  vim = "",
	  neovim = "",
  },
  toggle = {
	  on = "󰔡",
	  off = "󰨙",
  },
  state = {
	  loaded = "󰗠",
	  pending = "󰟃",
	  not_loaded = "󰄯",
  },
  modified = "󰑊",
	-- modified = "",
	-- modified = "󰑊",
	-- modified = "󰪥",
	hidden = "󰈉",
  init = "󰟒",
	key = "󰌆",
	-- start = "󰐊",
	start = "󰗍",
	setting = "󰒓",
	-- setting = "󰣖",
	server = "󰇖",
	restore = "󰑌",
	-- restore = "󱍷",
	-- restore = "󱍸",
	mark = "󰍎",
	flash = "󰉁",
	pin = "󰐃",
	terminal = "",
	favorite = "󰓎",
	-- favorite = "󰫢",
	sleep = "󰒲",
	plugin = "󰐱",
	-- plugin = "󱊈",
	-- plugin = "󱘖",
	runtime = "󰓅",
	require = "󰢱",
	-- require = "󰃀",
	source = "󰐤",
	-- source = "󰆦",
	task = "󱃔",
	label = "󰌕",
	save = "󰆓",
	buffers = "󰀻",
	record = "󰑊",
};

local kind_icons = {
  Text = "",
  Method = "",
  Function = "󰊕",
  Constructor = "",
  Field = "",
  Variable = "",
  Class = "",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "󰎠",
  Enum = "",
  Keyword = "",
  Snippet = "",
  Color = "",
  File = "",
  Reference = "",
  Folder = "",
  EnumMember = "",
  Constant = "",
  Struct = "",
  Event = "",
  Operator = "",
  TypeParameter = "",
}

M.separators = {
  left_1 = "",
	left_2 = "╱",
	right_1 = "",
	right_2 = "╲",
	left_3 = "▏", -- used only in lualine besides scrollbar
	right_3 = "▕", -- used only in lualine besides scrollbar
	-- left = "🙽",
	-- right = "🙼",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "▓▒░",
	-- right = "░▒▓",
};

M.indent_line = {
  default = "│",
	last = "╰",
	bottom = "─",
};

M.kind = {
	file = "󰈤",
	module = "󰆧",
	namespace = "󰧾",
	package = "󰏗",
	class = "",
	method = "󰮄",
	property = "",
	field = "",
	constructor = "",
	enum = "",
	interface = "󰒉",
	functions = "󰊕",
	variable = "󰫧",
	constant = "󱀍",
	number = "󰎠",
	boolean = "󰨚",
	array = "󰅪",
	object = "󰅩",
	key = "󰷖",
	value = "",
	null = "󰊓",
	enumMember = "",
	struct = "",
	event = "",
	operator = "󰆕",
	typeParameter = "",
	color = "󰸌",
	folder = "󰉖",
	keyword = "󰤱",
	reference = "󰷋",
	snippet = "󰏢",
	text = "󰀬",
	unit = "󰑭",
};

return M;
