local M = {};

M.ui = {
	close = "󱎘",
	quit = "󰍃",
	arrow_right = "󰳟",
	-- arrow_right = "󰬪",
	arrow_left = "󰳝",
	-- arrow_left = "󰬨",
};

M.git = {
	add = "󰐙",
	branch = "",
	conflict = "󱨧",
	diff = "󰆗",
	diffAlt = "",
	ignore = "󱥸",
	mod = "󰻃",
	octoface = "",
	remove = "󰜺",
	rename = "󰮍",
	repo = "",
	stage = "󰬭",
	stageAlt = "󰗡",
	tag = "",
	unstage = "󰬧",
	unstageAlt = "󰏦",
	untrack = "󰄰",
};

M.diagnostics = {
	error = "󰅙",
	hint = "󰌵",
	-- hint = "󱤅",
	info = "󰋼",
	ques = "󰋗",
	warn = "󰀦",
	-- warn = "󰀨",
	debug = "󰀦",
	trace = "󰀦",
};

M.documents = {
	file = "󰈔",
	file_writtened = "",
	file_import = "󰈠",
	file_find = "󰱼",
	file_add = "󰝒",
	file_recent = "󱋡",
	text_find = "󱎸",
	folders = "󰉓",
	folder_closed = "󰉋",
	folder_opened = "󰝰",
	folder_empty = "󰉖",
	folder_tree = "󰙅",
	modified = "",
	-- modified = "󰑊",
	-- modified = "󰪥",
	hidden = "󰈉",
};

M.others = {
	init = "󰟒",
	key = "󰌆",
	-- start = "󰐊",
	start = "󰗍",
	setting = "󰒓",
	-- setting = "󰣖",
	server = "󰇖",
	restore = "󰑌",
	-- restore = "󱍷",
	-- restore = "󱍸",
	mark = "󰍎",
	layer_find = "󱈆",
	session_find = "󰛔",
	flash = "󰉁",
	pin = "󰐃",
	terminal = "",
	favorite = "󰓎",
	-- favorite = "󰫢",
	sleep = "󰒲",
	loaded = "󰗠",
	pending = "󰟃",
	not_loaded = "󰄯",
	plugin = "󰐱",
	-- plugin = "󱊈",
	-- plugin = "󱘖",
	runtime = "󰓅",
	require = "󰢱",
	-- require = "󰃀",
	source = "󰐤",
	-- source = "󰆦",
	task = "󱃔",
	toggle_on = "󰔡",
	toggle_off = "󰨙",
	label = "󰌕",
	save = "󰆓",
};

M.separators = {
	left = "",
	right = "",
	-- left = "🙽",
	-- right = "🙼",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "",
	-- right = "",
	-- left = "╲",
	-- right = "╱",
	-- left = "▓▒░",
	-- right = "░▒▓",
};

M.kind = {
	file = " ",
	module = " ",
	namespace = " ",
	package = " ",
	class = " ",
	method = " ",
	property = " ",
	field = " ",
	constructor = " ",
	enum = " ",
	interface = " ",
	functions = " ",
	variable = " ",
	constant = " ",
	number = " ",
	boolean = " ",
	array = " ",
	object = " ",
	key = " ",
	null = " ",
	enumMember = " ",
	struct = " ",
	event = " ",
	operator = " ",
	typeParameter = " ",
	color = " ",
	folder = " ",
	keyword = " ",
	reference = " ",
	snippet = " ",
	text = " ",
	unit = " ",
	value = " ",
}

return M;
