{ pkgs, lib, ... }:
let
  hyprlandDir = ./.; # hyprland file directory (this directory)
  hyprlandFiles =
    builtins.filter (name: !(lib.elem name [ "default.nix" "hyprland.conf" ]))
    (builtins.attrNames (builtins.readDir
      hyprlandDir)); # filtering files, which should not symlink into ~/.config/hypr/

in {
  wayland = {
    windowManager = {
      hyprland = {
        enable = true;
        plugins = with pkgs; [ ];
        extraConfig = builtins.readFile
          "${hyprlandDir}/hyprland.conf"; # this is for, whatever we can't import the hyprland.conf, because of its conflicting with autogenerated hyprland.conf file by nixos. that's why we just read my hyprland.conf file here and put the all configs into existing autogenerated hyprland.conf file
      };
    };
  };

  home = {
    file = lib.mkMerge (map
      (fileName: # map means map loops in between all the files into this hyprlandDir
        let
          isScript = lib.hasSuffix ".sh" fileName;
          target = ".config/hypr/${fileName}";
        in {
          ${target} = {
            source = "${hyprlandDir}/${fileName}";
            # Make script files executable
            executable = isScript;
          };
        }) hyprlandFiles);
  };
}
