local M = {}

M.telescope_key = {
	["<leader>f"] = {
		desc = "[F]ind",
		-- a = { cmd = "<cmd>Telescope builtin<cr>", desc = "[A]ll" },
		-- b = { cmd = "<cmd>Telescope buffers<cr>", desc = "[B]uffers" },
		-- c = {
		-- 	desc = "[C]ommand",
		-- 	c = { cmd = "<cmd>Telescope commands<cr>", desc = "[C]ommand" },
		-- 	h = { cmd = "<cmd>Telescope command_history<cr>", desc = "[H]istory" },
		-- },
		-- C = { cmd = "<cmd>Telescope colorscheme<cr>", desc = "[C]olorscheme" },
		-- f = {
		-- 	desc = "[F]ile",
		-- 	a = { cmd = "<cmd>Telescope find_files<cr>", desc = "[A]ll" },
		-- 	c = { cmd = "<cmd>Telescope find_files cwd=~/.config<cr>", desc = "[C]onfig" },
		-- 	r = { cmd = "<cmd>Telescope oldfiles<cr>", desc = "[R]ecents" },
		-- },
		g = {
			desc = "[G]it",
			-- b = { cmd = "<cmd>Telescope git_branches<cr>", desc = "[B]ranches" },
			c = { cmd = "<cmd>Telescope git_commits<cr>", desc = "[C]ommits" },
			-- f = { cmd = "<cmd>Telescope git_files<cr>", desc = "[F]iles" },
			-- s = { cmd = "<cmd>Telescope git_status<cr>", desc = "[S]tatus" },
			-- S = { cmd = "<cmd>Telescope git_stash<cr>", desc = "[S]tash" },
		},
		-- h = { cmd = "<cmd>Telescope help_tags<cr>", desc = "[H]elp" },
		-- H = { cmd = "<cmd>Telescope highlights<cr>", desc = "[H]ighlights" },
		-- k = { cmd = "<cmd>Telescope keymaps<cr>", desc = "[K]eymaps" },
		-- l = {
		-- 	desc = "[L]sp",
		-- 	d = { cmd = "<cmd>Telescope diagnostics<cr>", desc = "[D]iagnostics" },
		-- 	c = {
		-- 		desc = "[C]alls",
		-- 		i = { cmd = "<cmd>Telescope lsp_incoming_calls<cr>", desc = "[I]ncoming" },
		-- 		o = { cmd = "<cmd>Telescope lsp_outgoing_calls<cr>", desc = "[O]utgoing" },
		-- 	},
		-- 	r = { cmd = "<cmd>Telescope lsp_references<cr>", desc = "[R]eferences" },
		-- 	s = {
		-- 		desc = "[S]ymbols",
		-- 		d = { cmd = "<cmd>Telescope lsp_document_symbols<cr>", desc = "[D]ocument" },
		-- 		w = { cmd = "<cmd>Telescope lsp_workspace_symbols<cr>", desc = "[W]orkspace" },
		-- 		D = { cmd = "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "[D]ynamic" },
		-- 	},
		-- 	t = { cmd = "<cmd>Telescope lsp_type_definitions<cr>", desc = "[T]ype definations" },
		-- },
		-- L = {
		-- 	desc = "[L]ist",
		-- 	j = { cmd = "<cmd>Telescope jumplist<cr>", desc = "[J]ump" },
		-- 	l = { cmd = "<cmd>Telescope loclist<cr>", desc = "[L]ocation" },
		-- 	q = {
		-- 		desc = "[Q]uickFix",
		-- 		q = { cmd = "<cmd>Telescope quickfix<cr>", desc = "[Q]uickfix" },
		-- 		h = { cmd = "<cmd>Telescope quickfixhistory<cr>", desc = "[H]istory" },
		-- 	},
		-- },
		-- m = { cmd = "<cmd>Telescope marks<cr>", desc = "[M]arks" },
		-- M = { cmd = "<cmd>Telescope media_files<cr>", desc = "[M]edia" },
		-- n = { cmd = "<cmd>Telescope noice<cr>", desc = "[N]otification" },
		o = { cmd = "<cmd>Telescope vim_options<cr>", desc = "[O]ptions" },
		-- w = {
		-- 	desc = "[W]ords",
		-- 	a = { cmd = "<cmd>Telescope live_grep<cr>", desc = "[A]ll" },
		-- 	c = { cmd = "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "[C]urrent" },
		-- 	C = { cmd = "<cmd>Telescope grep_string<cr>", desc = "[C]ursor" },
		-- },
		-- r = { cmd = "<cmd>Telescope registers<cr>", desc = "[R]egisters" },
		-- R = { cmd = "<cmd>Telescope resume<cr>", desc = "[R]esume" },
		-- s = { cmd = "<cmd>Telescope spell_suggest<cr>", desc = "[S]pell" },
		-- S = {
		-- 	desc = "[S]earch",
		-- 	h = { cmd = "<cmd>Telescope search_history<cr>", desc = "[H]istory" },
		-- },
		-- u = { cmd = "<cmd>Telescope undo<cr>", desc = "[U]ndo" },
	},
	["<leader>f<leader>"] = {
		desc = "Extras",
		-- a = { cmd = "<cmd>Telescope builtin<cr>", desc = "[A]ll" },
		-- b = { cmd = "<cmd>Telescope buffers<cr>", desc = "[B]uffers" },
		-- c = {
		-- 	desc = "[C]ommand",
		-- 	c = { cmd = "<cmd>Telescope commands<cr>", desc = "[C]ommand" },
		-- 	h = { cmd = "<cmd>Telescope command_history<cr>", desc = "[H]istory" },
		-- },
		-- C = { cmd = "<cmd>Telescope colorscheme<cr>", desc = "[C]olorscheme" },
		-- f = {
		-- 	desc = "[F]ile",
		-- 	a = { cmd = "<cmd>Telescope find_files<cr>", desc = "[A]ll" },
		-- 	c = { cmd = "<cmd>Telescope find_files cwd=~/.config<cr>", desc = "[C]onfig" },
		-- 	r = { cmd = "<cmd>Telescope oldfiles<cr>", desc = "[R]ecents" },
		-- },
		g = {
			desc = "[G]it",
			-- b = { cmd = "<cmd>Telescope git_branches<cr>", desc = "[B]ranches" },
			c = {
				desc = "[C]ommits",
				c = { cmd = "<cmd>Telescope git_bcommits<cr>", desc = "[C]urrent" },
			},
			-- f = { cmd = "<cmd>Telescope git_files<cr>", desc = "[F]iles" },
			-- s = { cmd = "<cmd>Telescope git_status<cr>", desc = "[S]tatus" },
			-- S = { cmd = "<cmd>Telescope git_stash<cr>", desc = "[S]tash" },
		},
		-- h = { cmd = "<cmd>Telescope help_tags<cr>", desc = "[H]elp" },
		-- H = { cmd = "<cmd>Telescope highlights<cr>", desc = "[H]ighlights" },
		-- k = { cmd = "<cmd>Telescope keymaps<cr>", desc = "[K]eymaps" },
		-- l = {
		-- 	desc = "[L]sp",
		-- 	d = { cmd = "<cmd>Telescope diagnostics<cr>", desc = "[D]iagnostics" },
		-- 	c = {
		-- 		desc = "[C]alls",
		-- 		i = { cmd = "<cmd>Telescope lsp_incoming_calls<cr>", desc = "[I]ncoming" },
		-- 		o = { cmd = "<cmd>Telescope lsp_outgoing_calls<cr>", desc = "[O]utgoing" },
		-- 	},
		-- 	r = { cmd = "<cmd>Telescope lsp_references<cr>", desc = "[R]eferences" },
		-- 	s = {
		-- 		desc = "[S]ymbols",
		-- 		d = { cmd = "<cmd>Telescope lsp_document_symbols<cr>", desc = "[D]ocument" },
		-- 		w = { cmd = "<cmd>Telescope lsp_workspace_symbols<cr>", desc = "[W]orkspace" },
		-- 		D = { cmd = "<cmd>Telescope lsp_dynamic_workspace_symbols<cr>", desc = "[D]ynamic" },
		-- 	},
		-- 	t = { cmd = "<cmd>Telescope lsp_type_definitions<cr>", desc = "[T]ype definations" },
		-- },
		-- L = {
		-- 	desc = "[L]ist",
		-- 	j = { cmd = "<cmd>Telescope jumplist<cr>", desc = "[J]ump" },
		-- 	l = { cmd = "<cmd>Telescope loclist<cr>", desc = "[L]ocation" },
		-- 	q = {
		-- 		desc = "[Q]uickFix",
		-- 		q = { cmd = "<cmd>Telescope quickfix<cr>", desc = "[Q]uickfix" },
		-- 		h = { cmd = "<cmd>Telescope quickfixhistory<cr>", desc = "[H]istory" },
		-- 	},
		-- },
		-- m = { cmd = "<cmd>Telescope marks<cr>", desc = "[M]arks" },
		-- M = { cmd = "<cmd>Telescope media_files<cr>", desc = "[M]edia" },
		-- n = { cmd = "<cmd>Telescope noice<cr>", desc = "[N]otification" },
		o = { cmd = "<cmd>Telescope vim_options<cr>", desc = "[O]ptions" },
		-- w = {
		-- 	desc = "[W]ords",
		-- 	a = { cmd = "<cmd>Telescope live_grep<cr>", desc = "[A]ll" },
		-- 	c = { cmd = "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "[C]urrent" },
		-- 	C = { cmd = "<cmd>Telescope grep_string<cr>", desc = "[C]ursor" },
		-- },
		-- r = { cmd = "<cmd>Telescope registers<cr>", desc = "[R]egisters" },
		-- R = { cmd = "<cmd>Telescope resume<cr>", desc = "[R]esume" },
		-- s = { cmd = "<cmd>Telescope spell_suggest<cr>", desc = "[S]pell" },
		-- S = {
		-- 	desc = "[S]earch",
		-- 	h = { cmd = "<cmd>Telescope search_history<cr>", desc = "[H]istory" },
		-- },
		-- u = { cmd = "<cmd>Telescope undo<cr>", desc = "[U]ndo" },
	},
}

M.fzf_key = {
	["<leader>f"] = {
		desc = "[F]ind",
		a = { cmd = "<cmd>FzfLua<cr>", desc = "[A]ll" },
		b = { cmd = "<cmd>FzfLua buffers<cr>", desc = "[B]uffers" },
		c = {
			desc = "[C]ommand",
			c = { cmd = "<cmd>FzfLua commands<cr>", desc = "[C]ommand" },
			h = { cmd = "<cmd>FzfLua command_history<cr>", desc = "[H]istory" },
		},
		C = {
			desc = "Colorscheme",
			c = { cmd = "<cmd>FzfLua colorscheme<cr>", desc = "[C]olorscheme" },
			m = { cmd = "<cmd>FzfLua awesome_colorschemes<cr>", desc = "[M]ore" },
		},
		d = {
			desc = "[D]iagnostics",
			d = { cmd = "<cmd>FzfLua diagnostics_document<cr>", desc = "[D]ocument" },
			w = { cmd = "<cmd>FzfLua diagnostics_workspace<cr>", desc = "[W]orkspace" },
		},
		f = {
			desc = "[F]ile",
			a = { cmd = "<cmd>FzfLua files<cr>", desc = "[A]ll" },
			c = { cmd = "<cmd>FzfLua files cwd=~/.config<cr>", desc = "[C]onfig" },
			r = { cmd = "<cmd>FzfLua oldfiles<cr>", desc = "[R]ecents" },
		},
		g = {
			desc = "[G]it",
			b = { cmd = "<cmd>FzfLua git_branches<cr>", desc = "[B]ranches" },
			B = { cmd = "<cmd>FzfLua git_blame<cr>", desc = "[B]lame" },
			d = { cmd = "<cmd>FzfLua git_diff<cr>", desc = "[D]iff" },
			c = {
				desc = "[C]ommits",
				b = { cmd = "<cmd>FzfLua git_bcommits<cr>", desc = "[B]uffer" },
				c = { cmd = "<cmd>FzfLua git_commits<cr>", desc = "[C]ommit" },
			},
			f = { cmd = "<cmd>FzfLua git_files<cr>", desc = "[F]iles" },
			h = { cmd = "<cmd>FzfLua git_hunks<cr>", desc = "[H]unks" },
			s = { cmd = "<cmd>FzfLua git_status<cr>", desc = "[S]tatus" },
			S = { cmd = "<cmd>FzfLua git_stash<cr>", desc = "[S]tash" },
			t = { cmd = "<cmd>FzfLua git_tags<cr>", desc = "[T]ags" },
		},
		h = { cmd = "<cmd>FzfLua help_tags<cr>", desc = "[H]elp" },
		H = { cmd = "<cmd>FzfLua highlights<cr>", desc = "[H]ighlights" },
		k = { cmd = "<cmd>FzfLua keymaps<cr>", desc = "[K]eymaps" },
		l = {
			desc = "[L]sp",
			a = { cmd = "<cmd>FzfLua lsp_code_actions<cr>", desc = "Code [A]ctions" },
			d = {
				desc = "[D]iagnostics",
				d = { cmd = "<cmd>FzfLua lsp_document_diagnostics<cr>", desc = "[D]ocument" },
				w = { cmd = "<cmd>FzfLua lsp_workspace_diagnostics<cr>", desc = "[W]orkspace" },
			},
			D = { cmd = "<cmd>FzfLua lsp_definitions<cr>", desc = "[D]efinitions" },
			c = {
				desc = "[C]alls",
				i = { cmd = "<cmd>FzfLua lsp_incoming_calls<cr>", desc = "[I]ncoming" },
				o = { cmd = "<cmd>FzfLua lsp_outgoing_calls<cr>", desc = "[O]utgoing" },
			},
			e = { cmd = "<cmd>FzfLua lsp_declarations<cr>", desc = "D[E]clarations" },
			f = { cmd = "<cmd>FzfLua lsp_finder<cr>", desc = "[F]inder" },
			r = { cmd = "<cmd>FzfLua lsp_references<cr>", desc = "[R]eferences" },
			i = { cmd = "<cmd>FzfLua lsp_implementations<cr>", desc = "[I]mplementations" },
			s = {
				desc = "[S]ymbols",
				d = { cmd = "<cmd>FzfLua lsp_document_symbols<cr>", desc = "[D]ocument" },
				w = { cmd = "<cmd>FzfLua lsp_workspace_symbols<cr>", desc = "[W]orkspace" },
				l = { cmd = "<cmd>FzfLua lsp_live_workspace_symbols<cr>", desc = "[L]ive" },
			},
			t = { cmd = "<cmd>FzfLua lsp_typedefs<cr>", desc = "[T]ype definations" },
		},
		L = {
			desc = "[L]ist",
			j = { cmd = "<cmd>FzfLua jumps<cr>", desc = "[J]ump" },
			l = {
				desc = "[L]ocation",
				l = { cmd = "<cmd>FzfLua loclist<cr>", desc = "[L]ocation" },
				s = { cmd = "<cmd>FzfLua loclist_stack<cr>", desc = "[S]tacks" },
			},
			q = {
				desc = "[Q]uickFix",
				q = { cmd = "<cmd>FzfLua quickfix<cr>", desc = "[Q]uickfix" },
				h = { cmd = "<cmd>FzfLua quickfix_stack<cr>", desc = "[H]istory" },
			},
		},
		m = { cmd = "<cmd>FzfLua marks<cr>", desc = "[M]arks" },
		M = { cmd = "<cmd>FzfLua media_files<cr>", desc = "[M]edia" },
		n = { cmd = "<cmd>FzfLua noice<cr>", desc = "[N]otification" },
		o = { cmd = "<cmd>FzfLua nvim_options<cr>", desc = "[O]ptions" },
		w = {
			desc = "[W]ords",
			a = { cmd = "<cmd>FzfLua live_grep<cr>", desc = "[A]ll" },
			b = { cmd = "<cmd>FzfLua grep_buffers<cr>", desc = "[B]uffers" },
			c = { cmd = "<cmd>FzfLua grep_curbuf<cr>", desc = "[C]urrent" },
			-- C = { cmd = "<cmd>FzfLua grep_string<cr>", desc = "[C]ursor" },
			v = { cmd = "<cmd>FzfLua grep_visual<cr>", desc = "[V]isual", mode = "v" },
		},
		r = { cmd = "<cmd>FzfLua registers<cr>", desc = "[R]egisters" },
		R = { cmd = "<cmd>FzfLua resume<cr>", desc = "[R]esume" },
		s = { cmd = "<cmd>FzfLua spell_suggest<cr>", desc = "[S]pell" },
		S = {
			desc = "[S]earch",
			h = { cmd = "<cmd>FzfLua search_history<cr>", desc = "[H]istory" },
		},
		-- u = { cmd = "<cmd>FzfLua undo<cr>", desc = "[U]ndo" },
	},
}

return M
